name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Build Docker image
        run: |
          docker build -t hello-alpine:${{ github.sha }}.

      - name: Tag Docker image
        run: |
          docker tag hello-alpine:${{ github.sha }} ghcr.io/J-Bunny560/hello-alpine:${{ github.sha }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/J-Bunny560/hello-alpine:${{ github.sha }}